#TO_DB Converter Configuration
#Fri Jun 12 10:22:18 CEST 2026
pattern.approximation.enrollments=grade\:1
pattern.attribute.employee_details=personal\=pesel\:PESEL,birth_date\:Data,bio\:Bio
pattern.computed.departments=employee_count\=COUNT(employees.id)
pattern.computed.employees=subordinate_count\=COUNT(employees.id)
pattern.computed.projects=participant_count\=COUNT(employee_projects.employee_id)
pattern.outlier.employees=activity_logs\=2
pattern.subset.employees=activity_logs\=3
relationship.strategy.activity_logs.employees=REFERENCE
relationship.strategy.default=EMBED
relationship.strategy.employee_details.employees=EMBED
relationship.strategy.employee_projects.employees=REFERENCE
relationship.strategy.employee_projects.projects=REFERENCE
relationship.strategy.employees.departments=EMBED
relationship.strategy.employees.employees=REFERENCE
safeguard.max_children_per_parent=1000
source.jdbc.password=password
source.jdbc.url=jdbc\:postgresql\://localhost\:5433/source_db
source.jdbc.username=postgres
target.mongodb.database=mydb_converted
target.mongodb.uri=mongodb\://admin\:password@localhost\:27018
