version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: to_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: source_db
    ports:
      - "5433:5432"
    volumes:
      - ./database/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d source_db"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - db_network

  mongodb:
    image: mongo:7
    container_name: to_db_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - db_network

volumes:
  postgres_data:
  mongo_data:

networks:
  db_network:
    driver: bridge
