# PostgreSQL Configuration
postgres.host=localhost
postgres.port=5433
postgres.database=source_db
postgres.username=postgres
postgres.password=postgres
postgres.schema=public

# MongoDB Configuration
mongo.host=localhost
mongo.port=27018
mongo.database=target_db
mongo.username=admin
mongo.password=admin

# Conversion Direction
# Options: MONGO_TO_POSTGRES, POSTGRES_TO_MONGO
conversion.direction=MONGO_TO_POSTGRES