# Config PostgreSQL
postgres.host=localhost
postgres.port=5433
postgres.database=source_db
postgres.user=postgres
postgres.password=postgres

# Config MongoDB
mongo.host=localhost
mongo.port=27018
mongo.database=target_db
mongo.user=admin
mongo.password=admin
